/** Builds a downloadable .pptx executive summary, structurally modeled on a
 * standard media-performance recap deck (title -> KPI banner -> investment
 * table -> channel chart) but skinned entirely in this product's own tokens
 * -- no colors, logos, or copy lifted from any reference deck. Every number
 * in it comes from the champion run's real contributions; nothing here is
 * fabricated or estimated beyond what the API already returns. */
import pptxgen from "pptxgenjs";

const INK = "14181F";
const INK_3 = "737D89";
const ACCENT = "3B3A8F";
const ACCENT_DIM = "EDEDF7";
const POS = "14795C";
const PANEL = "FFFFFF";
const SUNKEN = "F8F9FB";
const LINE = "E1E5EA";

export type ReportRow = { name: string; spend: number; revenue: number; roi: number; mroi: number };

export type ReportInputs = {
  title: string;
  periodLabel: string;
  comparisonLabel: string;
  clientName: string;
  projectName: string;
  runId: string;
  rSquared: number | null;
  holdoutMape: number | null;
  totalSpend: number;
  totalRevenue: number;
  rows: ReportRow[];
};

function money(v: number) {
  return v >= 1 ? "£" + v.toFixed(2) + "M" : "£" + Math.round(v * 1000) + "K";
}

export async function buildReportDeck(inputs: ReportInputs): Promise<Blob> {
  const pptx = new pptxgen();
  pptx.defineLayout({ name: "WIDE", width: 13.33, height: 7.5 });
  pptx.layout = "WIDE";

  const sorted = inputs.rows.slice().sort((a, b) => b.spend - a.spend);
  const avgRoi = inputs.totalSpend > 0 ? inputs.totalRevenue / inputs.totalSpend : 0;

  // --- Title slide ---------------------------------------------------
  const title = pptx.addSlide();
  title.background = { color: PANEL };
  title.addShape("rect", { x: 0, y: 0, w: 13.33, h: 1.3, fill: { color: ACCENT } });
  title.addText(inputs.clientName || "Confidential", { x: 0.5, y: 0.35, w: 8, h: 0.6, fontSize: 12, color: "FFFFFF", bold: true });
  title.addText(inputs.title, { x: 0.7, y: 2.3, w: 12, h: 1.2, fontSize: 32, color: INK, bold: true });
  title.addText(`${inputs.projectName} · ${inputs.periodLabel}${inputs.comparisonLabel ? " vs " + inputs.comparisonLabel : ""}`, {
    x: 0.7,
    y: 3.35,
    w: 12,
    h: 0.5,
    fontSize: 15,
    color: INK_3,
  });
  title.addText(
    `Champion run ${inputs.runId.slice(0, 8)} · R² ${inputs.rSquared ?? "—"} · holdout MAPE ${inputs.holdoutMape ?? "—"}%`,
    { x: 0.7, y: 3.9, w: 12, h: 0.4, fontSize: 11, color: INK_3 }
  );
  title.addText("Generated by MMM Platform — figures trace to the champion model's cached contributions", {
    x: 0.5,
    y: 7.0,
    w: 12.3,
    h: 0.35,
    fontSize: 9,
    color: INK_3,
  });

  // --- KPI summary slide -----------------------------------------------
  const kpi = pptx.addSlide();
  kpi.background = { color: PANEL };
  kpi.addText("Marketing performance summary", { x: 0.5, y: 0.35, w: 10, h: 0.5, fontSize: 20, bold: true, color: INK });
  kpi.addText(`${inputs.periodLabel}${inputs.comparisonLabel ? " vs " + inputs.comparisonLabel : ""}`, {
    x: 0.5,
    y: 0.85,
    w: 10,
    h: 0.35,
    fontSize: 12,
    color: INK_3,
  });

  const kpis: [string, string][] = [
    ["Media spend", money(inputs.totalSpend)],
    ["Incremental revenue", money(inputs.totalRevenue)],
    ["Media ROI", avgRoi.toFixed(2)],
    ["Channels", String(inputs.rows.length)],
  ];
  const cardW = 2.9;
  kpis.forEach(([label, value], i) => {
    const x = 0.5 + i * (cardW + 0.25);
    kpi.addShape("roundRect", { x, y: 1.5, w: cardW, h: 1.6, fill: { color: SUNKEN }, line: { color: LINE, width: 1 }, rectRadius: 0.06 });
    kpi.addText(value, { x, y: 1.65, w: cardW, h: 0.8, align: "center", fontSize: 26, bold: true, color: ACCENT });
    kpi.addText(label, { x, y: 2.35, w: cardW, h: 0.5, align: "center", fontSize: 11, color: INK_3 });
  });

  kpi.addText("Media investment by channel", { x: 0.5, y: 3.5, w: 10, h: 0.4, fontSize: 14, bold: true, color: INK });
  kpi.addChart(
    pptx.ChartType.bar,
    [
      {
        name: "Spend",
        labels: sorted.map((r) => r.name),
        values: sorted.map((r) => Number(r.spend.toFixed(2))),
      },
    ],
    { x: 0.5, y: 3.9, w: 12.3, h: 3.2, barDir: "col", chartColors: [ACCENT], showValue: true, dataLabelColor: INK, catAxisLabelColor: INK_3, valAxisLabelColor: INK_3 }
  );

  // --- Channel table slide ----------------------------------------------
  const table = pptx.addSlide();
  table.background = { color: PANEL };
  table.addText("Channel investment & return", { x: 0.5, y: 0.35, w: 10, h: 0.5, fontSize: 20, bold: true, color: INK });
  table.addText(`${inputs.periodLabel} · ranked by spend`, { x: 0.5, y: 0.85, w: 10, h: 0.35, fontSize: 12, color: INK_3 });

  const header = ["Channel", "Spend", "Incr. revenue", "ROI", "Marginal ROI"].map((t) => ({
    text: t,
    options: { bold: true, color: "FFFFFF", fill: { color: ACCENT }, fontSize: 11 },
  }));
  const rows = sorted.map((r) => [
    { text: r.name, options: { fontSize: 10.5, color: INK } },
    { text: money(r.spend), options: { fontSize: 10.5, color: INK, align: "right" as const } },
    { text: money(r.revenue), options: { fontSize: 10.5, color: INK, align: "right" as const } },
    { text: r.roi.toFixed(2), options: { fontSize: 10.5, color: r.roi >= avgRoi ? POS : INK, align: "right" as const } },
    { text: r.mroi.toFixed(2), options: { fontSize: 10.5, color: INK, align: "right" as const } },
  ]);
  const totalRow = [
    { text: "Total", options: { bold: true, fontSize: 10.5, color: INK, fill: { color: ACCENT_DIM } } },
    { text: money(inputs.totalSpend), options: { bold: true, fontSize: 10.5, color: INK, align: "right" as const, fill: { color: ACCENT_DIM } } },
    { text: money(inputs.totalRevenue), options: { bold: true, fontSize: 10.5, color: INK, align: "right" as const, fill: { color: ACCENT_DIM } } },
    { text: avgRoi.toFixed(2), options: { bold: true, fontSize: 10.5, color: INK, align: "right" as const, fill: { color: ACCENT_DIM } } },
    { text: "—", options: { bold: true, fontSize: 10.5, color: INK, align: "right" as const, fill: { color: ACCENT_DIM } } },
  ];
  table.addTable([header, ...rows, totalRow], {
    x: 0.5,
    y: 1.4,
    w: 12.3,
    colW: [4.3, 2, 2, 2, 2],
    border: { type: "solid", color: LINE, pt: 0.5 },
    autoPage: false,
  });

  table.addText(
    "Figures are the champion run's cached per-channel contributions at the whole-project level — not a live " +
      "refresh against updated ingestion data.",
    { x: 0.5, y: 6.9, w: 12.3, h: 0.4, fontSize: 9, color: INK_3, italic: true }
  );

  return (await pptx.write({ outputType: "blob" })) as Blob;
}
